import Config

# Configure your database
config :fuzzy_catalog, FuzzyCatalog.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "fuzzy_catalog_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :fuzzy_catalog, FuzzyCatalogWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "eL71GeXGZmH6As2Py8a4GYb9TO3ZTxhoQJ9dfUcSh3eRW6bV6A9ML+ij+ou+8wb2",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:fuzzy_catalog, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:fuzzy_catalog, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :fuzzy_catalog, FuzzyCatalogWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/fuzzy_catalog_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :fuzzy_catalog, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Book lookup providers for development
# Uncomment to enable Google Books as fallback provider
# config :fuzzy_catalog, :book_lookup,
#   providers: [
#     FuzzyCatalog.Catalog.Providers.OpenLibraryProvider,
#     FuzzyCatalog.Catalog.Providers.GoogleBooksProvider
#   ]

# Audiobookshelf configuration for development
config :fuzzy_catalog, :audiobookshelf,
  url: System.get_env("AUDIOBOOKSHELF_URL"),
  api_key: System.get_env("AUDIOBOOKSHELF_API_KEY"),
  libraries: System.get_env("AUDIOBOOKSHELF_LIBRARIES")

# Storage configuration for development
config :fuzzy_catalog, :storage,
  local: [
    base_path: System.get_env("UPLOAD_PATH") || "priv/static/uploads/covers",
    base_url: "/uploads/covers"
  ]
